name: Publish

on:
  push:
    branches:
      - main

jobs:
  sign:
    name: Sign environment
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
  release:
    name: Release build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Release build
        # assembleRelease for all modules, excluding app
        run: ./gradlew assembleRelease -x :app:assembleRelease
      - name: Source jar
        run: ./gradlew androidSourcesJar javadocJar
      - name: Sign
        run: ./gradlew signReleasePublication